### ISSUE TITLE
MDBtoSQL deberia ir en un dbcommon con fuciones de exportacion

### ISSUE THREAD

**Issue by mckaygerhard** [belmotek/gambas-extra-functions#2]
MDBtoSQL deberia ir en una libreria tipo framework que realizara las conversiones...

**Comment by 64sys** [comment]
Estudiare el tema, ahora estoy preparando una nueva versión e incluiré ejemplos en uno o varios formularios para probar las funciones.
Saludos y gracias por comentar y opinar.

**Comment by mckaygerhard** [comment]
te tengo nuevas noticias, si no tiene buen soporte odbc y solo anda con mysql no creo sea un MDBtoSQL sino "toMysql" lo cual teniendo vision es muy limitado...
